version: "3.8"
services:
  mysql:
    container_name: mysql_local
    image: mysql:8.0.34
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=pass_local951
      - MYSQL_USER=pass_local_user951
      - MYSQL_PASSWORD=passlocal123951
      - MYSQL_ROOT_PASSWORD=passlocal123951
      - TZ=Asia/Seoul